// src/data/productsData.js

const productsData = [
    {
        id: 1,
        image: require('../Page/product.svg').default,
        isNew: true,
        isFavorite: false,
        category: 'POPCORN PASSION',
        title: 'Gourmet Caramel Popcorn With Classic Salt',
        description: 'Uninhibited carnally hired played in whimpered dear gorilla koala  depending and much yikes off far quetzal goodness and from for grimaced  goodness unaccountably and meadowlark near unblushingly crucial scallop  tightly neurotic hungrily some and dear furiously this apart.',
        longdescription: 'Pellentesque habitant morbi tristique senectus et netus et malesuada  fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,  ultricies eget, tempor sit amet, ante. ibero sit amet quam egestas  semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.ea  commodo consat. Duis aute irure dolor in reprehenderit n volup tate  velitesse cillum dolore euy elit ale ruin irure dolor.uis aute irure  dolor in reprehenderit n volup tate velit esse cillum,',
        rating: 5,
        originalPrice: 200.00,
        sku: 'BG-1008',
        minQty: '100',
        link: '#'
    },
    {
        id: 2,
        image: require('../Page/product.svg').default,
        isNew: true,
        isFavorite: false,
        category: 'POPCORN PASSION',
        title: 'Gourmet Caramel Popcorn With Classic Salt',
        description: 'Uninhibited carnally hired played in whimpered dear gorilla koala  depending and much yikes off far quetzal goodness and from for grimaced  goodness unaccountably and meadowlark near unblushingly crucial scallop  tightly neurotic hungrily some and dear furiously this apart.',
        longdescription: 'Pellentesque habitant morbi tristique senectus et netus et malesuada  fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,  ultricies eget, tempor sit amet, ante. ibero sit amet quam egestas  semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.ea  commodo consat. Duis aute irure dolor in reprehenderit n volup tate  velitesse cillum dolore euy elit ale ruin irure dolor.uis aute irure  dolor in reprehenderit n volup tate velit esse cillum,',
        rating: 5,
        originalPrice: 300.00,
        sku: 'BG-1008',
        minQty: '100',
        link: '#'
    },
    {
        id: 3,
        image: require('../Page/product.svg').default,
        isNew: false,
        isFavorite: false,
        category: 'POPCORN PASSION',
        title: 'Gourmet Caramel Popcorn With Classic Salt',
        description: 'Uninhibited carnally hired played in whimpered dear gorilla koala  depending and much yikes off far quetzal goodness and from for grimaced  goodness unaccountably and meadowlark near unblushingly crucial scallop  tightly neurotic hungrily some and dear furiously this apart.',
        longdescription: 'Pellentesque habitant morbi tristique senectus et netus et malesuada  fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,  ultricies eget, tempor sit amet, ante. ibero sit amet quam egestas  semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.ea  commodo consat. Duis aute irure dolor in reprehenderit n volup tate  velitesse cillum dolore euy elit ale ruin irure dolor.uis aute irure  dolor in reprehenderit n volup tate velit esse cillum,',
        rating: 5,
        originalPrice: 250.00,
        sku: 'BG-1008',
        minQty: '100',
        link: '#'
    },
    {
        id: 4,
        image: require('../Page/product.svg').default,
        isNew: false,
        isFavorite: false,
        category: 'POPCORN PASSION',
        title: 'Gourmet Caramel Popcorn With Classic Salt',
        description: 'Uninhibited carnally hired played in whimpered dear gorilla koala  depending and much yikes off far quetzal goodness and from for grimaced  goodness unaccountably and meadowlark near unblushingly crucial scallop  tightly neurotic hungrily some and dear furiously this apart.',
        longdescription: 'Pellentesque habitant morbi tristique senectus et netus et malesuada  fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,  ultricies eget, tempor sit amet, ante. ibero sit amet quam egestas  semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.ea  commodo consat. Duis aute irure dolor in reprehenderit n volup tate  velitesse cillum dolore euy elit ale ruin irure dolor.uis aute irure  dolor in reprehenderit n volup tate velit esse cillum,',
        rating: 5,
        originalPrice: 260.00,
        sku: 'BG-1008',
        minQty: '100',
        link: '#'
    },
    {
        id: 5,
        image: require('../Page/product.svg').default,
        isNew: true,
        isFavorite: false,
        category: 'POPCORN PASSION',
        title: 'Gourmet Caramel Popcorn With Classic Salt',
        description: 'Uninhibited carnally hired played in whimpered dear gorilla koala  depending and much yikes off far quetzal goodness and from for grimaced  goodness unaccountably and meadowlark near unblushingly crucial scallop  tightly neurotic hungrily some and dear furiously this apart.',
        longdescription: 'Pellentesque habitant morbi tristique senectus et netus et malesuada  fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,  ultricies eget, tempor sit amet, ante. ibero sit amet quam egestas  semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.ea  commodo consat. Duis aute irure dolor in reprehenderit n volup tate  velitesse cillum dolore euy elit ale ruin irure dolor.uis aute irure  dolor in reprehenderit n volup tate velit esse cillum,',
        rating: 5,
        originalPrice: 200.00,
        sku: 'BG-1008',
        minQty: '100',
        link: '#'
    },
    {
        id: 6,
        image: require('../Page/product.svg').default,
        isNew: true,
        isFavorite: false,
        category: 'POPCORN PASSION',
        title: 'Gourmet Caramel Popcorn With Classic Salt',
        description: 'Uninhibited carnally hired played in whimpered dear gorilla koala  depending and much yikes off far quetzal goodness and from for grimaced  goodness unaccountably and meadowlark near unblushingly crucial scallop  tightly neurotic hungrily some and dear furiously this apart.',
        longdescription: 'Pellentesque habitant morbi tristique senectus et netus et malesuada  fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,  ultricies eget, tempor sit amet, ante. ibero sit amet quam egestas  semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.ea  commodo consat. Duis aute irure dolor in reprehenderit n volup tate  velitesse cillum dolore euy elit ale ruin irure dolor.uis aute irure  dolor in reprehenderit n volup tate velit esse cillum,',
        rating: 5,
        originalPrice: 300.00,
        sku: 'BG-1008',
        minQty: '100',
        link: '#'
    },
    {
        id: 7,
        image: require('../Page/product.svg').default,
        isNew: false,
        isFavorite: false,
        category: 'POPCORN PASSION',
        title: 'Gourmet Caramel Popcorn With Classic Salt',
        description: 'Uninhibited carnally hired played in whimpered dear gorilla koala  depending and much yikes off far quetzal goodness and from for grimaced  goodness unaccountably and meadowlark near unblushingly crucial scallop  tightly neurotic hungrily some and dear furiously this apart.',
        longdescription: 'Pellentesque habitant morbi tristique senectus et netus et malesuada  fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,  ultricies eget, tempor sit amet, ante. ibero sit amet quam egestas  semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.ea  commodo consat. Duis aute irure dolor in reprehenderit n volup tate  velitesse cillum dolore euy elit ale ruin irure dolor.uis aute irure  dolor in reprehenderit n volup tate velit esse cillum,',
        rating: 5,
        originalPrice: 250.00,
        sku: 'BG-1008',
        minQty: '100',
        link: '#'
    },
    {
        id: 8,
        image: require('../Page/product.svg').default,
        isNew: false,
        isFavorite: false,
        category: 'POPCORN PASSION',
        title: 'Gourmet Caramel Popcorn With Classic Salt',
        description: 'Uninhibited carnally hired played in whimpered dear gorilla koala  depending and much yikes off far quetzal goodness and from for grimaced  goodness unaccountably and meadowlark near unblushingly crucial scallop  tightly neurotic hungrily some and dear furiously this apart.',
        longdescription: 'Pellentesque habitant morbi tristique senectus et netus et malesuada  fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,  ultricies eget, tempor sit amet, ante. ibero sit amet quam egestas  semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.ea  commodo consat. Duis aute irure dolor in reprehenderit n volup tate  velitesse cillum dolore euy elit ale ruin irure dolor.uis aute irure  dolor in reprehenderit n volup tate velit esse cillum,',
        rating: 5,
        originalPrice: 260.00,
        sku: 'BG-1008',
        minQty: '100',
        link: '#'
    },
];

export default productsData;
